// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjmtfoyqafsggfoupcuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqbXRmb3lxYWZzZ2dmb3VwY3VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MDEyMDQsImV4cCI6MjA2NTI3NzIwNH0.156JIcj94Vj7AJJqZ1PrvzatQ16RMe3vphEcK7inTxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);